# Native macOS Clang -> Linux x86-64. Never search Homebrew for target libraries.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
foreach(required VCS_STEAMDECK_SYSROOT VCS_LLVM_ROOT VCS_LLD)
    if(NOT DEFINED ENV{${required}})
        message(FATAL_ERROR "${required} is missing; use tools/build.sh --steamdeck")
    endif()
endforeach()
set(CMAKE_SYSROOT "$ENV{VCS_STEAMDECK_SYSROOT}")
set(CMAKE_CXX_COMPILER "$ENV{VCS_LLVM_ROOT}/bin/clang++")
set(CMAKE_CXX_COMPILER_TARGET x86_64-unknown-linux-gnu)
set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN "${CMAKE_SYSROOT}/usr")
set(CMAKE_AR "$ENV{VCS_LLVM_ROOT}/bin/llvm-ar")
set(CMAKE_RANLIB "$ENV{VCS_LLVM_ROOT}/bin/llvm-ranlib")
set(CMAKE_STRIP "$ENV{VCS_LLVM_ROOT}/bin/llvm-strip")
set(CMAKE_LINKER "$ENV{VCS_LLD}")
set(CMAKE_CXX_FLAGS_INIT "--no-default-config -stdlib=libstdc++")
set(CMAKE_EXE_LINKER_FLAGS_INIT "--ld-path=\"${CMAKE_LINKER}\" --rtlib=libgcc --unwindlib=libgcc -Wl,-rpath-link,${CMAKE_SYSROOT}/usr/lib/x86_64-linux-gnu")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_FRAMEWORK NEVER)
set(CMAKE_FIND_APPBUNDLE NEVER)
# No build-machine/sysroot absolute paths in the delivered ELF's dynamic paths.
set(CMAKE_SKIP_RPATH TRUE)
